approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: false
reviewers:
  - vkuruturi
  - bridgetbissell
  members:
  - vkuruturi
  - bridgetbissell
  - ccnezin
  name: default
  required: 2
